name: Build and deploy Docker Image

on:
  workflow_call:

jobs:
  build-discord-bot:
    name: Build Discord Bot Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Docker meta
      #   id: docker_meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ghcr.io/bifrostlab/llm-assistant
      #     tags: |
      #       type=ref,event=branch
      #       type=sha
      #       type=raw,value=production

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to GitHub Docker
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and Push docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     pull: true
      #     push: true
      #     target: production
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache
      #     tags: ${{ steps.docker_meta.outputs.tags }}
